# Creates a build every commit

name: Auto Build
on: 
  push:
    branches: [master,main]
    paths-ignore:
      - '**.yml'
      - '!.github/workflows/build.yml'
      - '.gitignore'
  pull_request:
    branches: [master,main]

jobs:
  auto-build:
    name: Auto Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build mod
      uses: ./.github/actions/build
